# profiles.yml

traffic:
  target: dev
  outputs:

    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      pass: Sheila@49
      dbname: TrafficDWH
      schema: public
